# Generated by Django 5.0.4 on 2024-04-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=10)),
                ('wind_gust_direction', models.CharField(max_length=20)),
                ('wind_gust', models.CharField(max_length=20)),
                ('dewpoint', models.CharField(max_length=10)),
                ('precip_rate', models.CharField(max_length=10)),
                ('pressure', models.CharField(max_length=10)),
                ('humidity', models.CharField(max_length=10)),
                ('precip_accum', models.CharField(max_length=10)),
                ('uv', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
