# Generated by Django 5.0.4 on 2024-04-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='fonte',
            field=models.CharField(choices=[('1', 'Pico do Caledônia'), ('2', 'Stucky'), ('3', 'Barão (Jardim Califórnia)'), ('4', 'Edifício Itália (Centro)')], max_length=1, null=True),
        ),
    ]
