# Generated by Django 5.0.4 on 2024-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0002_weatherdata_fonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='fonte',
            field=models.CharField(choices=[('1', 'Pico do Caledônia'), ('2', 'Stucky'), ('3', 'Barão (Jardim Califórnia)'), ('4', 'Edifício Itália (Centro)')], max_length=1, null=True, verbose_name='Fonte/Estação'),
        ),
    ]
