# Generated by Django 5.0.4 on 2025-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0003_datasource_alter_weatherdata_fonte'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Estação')),
                ('url', models.URLField(verbose_name='URL da Estação')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Observações/Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sugestão de Estação',
                'verbose_name_plural': 'Sugestões de Estações',
                'ordering': ['-created_at'],
            },
        ),
    ]
