# Generated by Django 5.0.4 on 2025-07-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraper', '0004_stationsuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='fonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraper.datasource', verbose_name='Fonte/Estação'),
        ),
    ]
